org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.newDsl=false
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# Avoid Kotlin incremental cache failures when project (D:) and pub-cache (C:) differ
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
